<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        <?php
        // put your code here
        //01 - C
        
        //*A PROGRAMAÇÃO ORIENTADA A OBJETOS SE PREOCUPA EM PRODUZIR SOFTWARE QUE TENHAS AS SEGUINTES CARACTERISTICAS;
        //02 - A - NATURAL, CONFIAVEL, REUTILIZÁVEL, MANUTENÍVEL, EXTENSÍVEL E OPORTUNO.
        
        // ALTERNATIVA ERRADA -SOBRE ORIENTAÇÃO OBJETO
        ////03 A - UMA CLASSE É INSTANCIA DE UM OBJETO
        
        //*04 - B - 3 2 1 5 4
        
        //05 -  C
        
        //*06 - 2 4 3 1 - C
        
        //TRES BASES DA ORIENTAÇÃO OBJETO
        //07 - C - HERANÇA, POLIMORFISMO E ENCAPSULAMENTO
        
        //08 - 2 4 1 3 - D
        
        //A MAIORIA DAS LINGUAGENS ORIENTADAS A OBJETOS SUPORTA QUAIS NIVEIS DE ACESSO
        //09 - B - PUBLICO - PROTEGIDO E PRIVADO
        
        //NO CONTEXTO DOS NIVEIS DE ACESSO SELECIONE A ALTERNATIVA QUE CONTEM O NIVEL QUE APENAS
        //GARANTE ACESSO PARA AQUELE OBJETO E SUAS SUBCLASSES
        //10 - B - PROTEGIDO
        
        //A PROTEÇÃO DE ATRIBUTOS E OPERAÇÕES DAS CLASSES, FAZEM COM QUE ESTAS SE COMUNIQUEM COM
        //O MEIO EXTERNO POR MEIO DE SUAS INTERFACES, DEFINE O CONCEITO DE:
        //B - ENCASULAMENTO
        
        //QUANDO SE UTILIZA P CONCEITO DE ENCASULAMENTO DA POO, ENQUANTO A_____ DEFINE
        //OS DETALHES INTERNOS DO COMPORTAMENTO, A _______ LISTA OS SERVIÇOS FORNECIDOS POR ELE.
        // D - IMPLEMENTAÇÃO - INTERFACE
        
        //*_________ É A CARACTERISTICA DA POO QUE PERMITE SEPARAR O PROGRAMA EM VARIAS PARTES MENORES E INDEPENDENTES.
        //CADA PARTE POSSUI SUA IMPLEMENTAÇÃO ISOLADA E REALIZA SEU TRABALHO DE FORMA AUTONOMA.
        //COM ESSA CARACTERISTICA É POSSIVEL OCULTAR OS DETALHES INTERNOS DE CADA PARTE ATRAVES DE UMA INTERFACE.
        // D - ENCAPSULAMENTO
        
        //QUAL CONCEITO EM  POO QUE SIGNIFICA REPRESENTAR UMA ENTIDADE, INCLUINDO APENAS SEUS ATRIBUTOS MAIS RELEVANTES
        //D - ABSTRAÇÃO
        
        //COM RELAÇÃO AOS CONCEITOS DE POO, ASSINALE A OPÇÃO INCORRETA.
        // D
        
        
        
        ?>
    </body>
</html>
